packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^5.3.0
    '@antfu/ni': ^25.0.0
    '@leafer-in/editor': 1.9.6
    '@leafer-in/interface': 1.9.6
    '@leafer-in/resize': 1.9.6
    '@leafer-in/view': 1.9.6
    '@leafer-in/viewport': 1.9.6
    '@leafer-ui/core': 1.9.6
    '@leafer-ui/interface': 1.9.6
    '@tsconfig/node22': ^22.0.2
    bumpp: ^10.1.0
    eslint: ^9.35.0
    leafer-ui: 1.9.6
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.11.1
    tsx: ^4.20.5
    typescript: ^5.8.2
    unbuild: ^3.6.1
    vite: ^7.1.5
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^24.3.1
  utils:
    tinyexec: ^1.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
